language: cpp
before_script:
- echo "Run before_script"
- sudo apt update -qq
- sudo apt install -y libboost-test-dev
script:
- cmake .
- cmake --build .
- ctest
- cmake --build . --target package
deploy:
    provider: script
    skip_cleanup: true
    script:
    - echo "Deploying version $TRAVIS_BUILD_NUMBER ..."
