language: cpp
before_script:
- echo "Run before_script"
- sudo apt update -qq
- sudo apt install -y libboost-test-dev
script:
- cmake .
- cmake --build .
- ctest
- cmake --build . --target package
deploy:
    provider: script
    skip_cleanup: true
    script:
    - curl --fail --show-error -T helloworld-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ufelixpalta:$BINTRAY_API_KEY "https://api.bintray.com/content/felixpalta/otus-cpp-repo/helloworld/$TRAVIS_BUILD_NUMBER/helloworld-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=wheezy;deb_component=main;deb_architecture=amd64"
